name: sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

# see https://github.com/marketplace/actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: kai-morich/usb-serial-for-android-mik3y
          ref: master
          token: ${{ secrets.SYNC_PAT }}  
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add base https://github.com/mik3y/usb-serial-for-android.git
          git fetch base
          git rebase base/master
          git push
